on: push
name: teste deploy
jobs:
  web-deploy:
    name: 🚀 deploy do zap(mains)
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: 167.114.153.47
        remote-user: root
        private-ssh-key: ${{ secrets.SSH_KEY }}
        ssh-port: 22
        destination-path: ~/var/www/html/zap/





